function getRandomImage() {  
    //declare an array to store the images  
    var randomImage = new Array();  

    //insert the URL of images in array  
    randomImage[0] = "https://d1u1mce87gyfbn.cloudfront.net/hero/ana/hero-select-portrait.png";
    randomImage[1] = "https://d1u1mce87gyfbn.cloudfront.net/hero/ashe/hero-select-portrait.png";
    randomImage[2] = "https://d1u1mce87gyfbn.cloudfront.net/hero/baptiste/hero-select-portrait.png";
    randomImage[3] = "https://d1u1mce87gyfbn.cloudfront.net/hero/bastion/hero-select-portrait.png";
    randomImage[5] = "https://d1u1mce87gyfbn.cloudfront.net/hero/brigitte/hero-select-portrait.png";
    randomImage[6] = "https://d1u1mce87gyfbn.cloudfront.net/hero/dva/hero-select-portrait.png";
    randomImage[7] = "https://d1u1mce87gyfbn.cloudfront.net/hero/doomfist/hero-select-portrait.png";
    randomImage[8] = "https://d1u1mce87gyfbn.cloudfront.net/hero/echo/hero-select-portrait.png";
    randomImage[9] = "https://d1u1mce87gyfbn.cloudfront.net/hero/genji/hero-select-portrait.png";
    randomImage[10] = "https://d1u1mce87gyfbn.cloudfront.net/hero/hanzo/hero-select-portrait.png";
    randomImage[11] = "https://d1u1mce87gyfbn.cloudfront.net/hero/junkrat/hero-select-portrait.png";
    randomImage[12] = "https://d1u1mce87gyfbn.cloudfront.net/hero/lucio/hero-select-portrait.png";
    randomImage[13] = "https://d1u1mce87gyfbn.cloudfront.net/hero/mccree/hero-select-portrait.png";
    randomImage[14] = "https://d1u1mce87gyfbn.cloudfront.net/hero/mei/hero-select-portrait.png";
    randomImage[15] = "https://d1u1mce87gyfbn.cloudfront.net/hero/mercy/hero-select-portrait.png";
    randomImage[16] = "https://d1u1mce87gyfbn.cloudfront.net/hero/moira/hero-select-portrait.png";
    randomImage[17] = "https://d1u1mce87gyfbn.cloudfront.net/hero/orisa/hero-select-portrait.png";
    randomImage[18] = "https://d1u1mce87gyfbn.cloudfront.net/hero/pharah/hero-select-portrait.png";
    randomImage[19] = "https://d1u1mce87gyfbn.cloudfront.net/hero/reaper/hero-select-portrait.png";
    randomImage[20] = "https://d1u1mce87gyfbn.cloudfront.net/hero/reinhardt/hero-select-portrait.png";
    randomImage[21] = "https://d1u1mce87gyfbn.cloudfront.net/hero/roadhog/hero-select-portrait.png";
    randomImage[22] = "https://d1u1mce87gyfbn.cloudfront.net/hero/sigma/hero-select-portrait.png";
    randomImage[23] = "https://d1u1mce87gyfbn.cloudfront.net/hero/soldier-76/hero-select-portrait.png";
    randomImage[24] = "https://d1u1mce87gyfbn.cloudfront.net/hero/sombra/hero-select-portrait.png";
    randomImage[25] = "https://d1u1mce87gyfbn.cloudfront.net/hero/symmetra/hero-select-portrait.png";
    randomImage[26] = "https://d1u1mce87gyfbn.cloudfront.net/hero/torbjorn/hero-select-portrait.png";
    randomImage[27] = "https://d1u1mce87gyfbn.cloudfront.net/hero/tracer/hero-select-portrait.png";
    randomImage[28] = "https://d1u1mce87gyfbn.cloudfront.net/hero/widowmaker/hero-select-portrait.png";
    randomImage[29] = "https://d1u1mce87gyfbn.cloudfront.net/hero/winston/hero-select-portrait.png";
    randomImage[30] = "https://d1u1mce87gyfbn.cloudfront.net/hero/wrecking-ball/hero-select-portrait.png";
    randomImage[31] = "https://d1u1mce87gyfbn.cloudfront.net/hero/zarya/hero-select-portrait.png";
    randomImage[32] = "https://d1u1mce87gyfbn.cloudfront.net/hero/zenyatta/hero-select-portrait.png";

//loop to display five randomly chosen images at once  
for (let i=0; i< 6; i++) {  
//generate a number and provide to the image to generate randomly  
var number = Math.floor(Math.random()*randomImage.length+1);  
//print the images generated by a random number  
document.getElementById("result").innerHTML += '<img src="'+ randomImage[number] +'" style="width:150px" />';  
}  
}  